package com.zweigbergk.speedswede.util.async;

public enum PromiseNeed {
    ID, NAME, TIMESTAMP, FIRST_USER, SECOND_USER, LIST, MESSAGE_LIST, ASSERTION, NOTIFICATIONS,
    LANGUAGE, USAGE, LAYOUT_MANAGER, CHAT, TRANSLATION, USER_ID_LIST, FIRST_ASSERTION,
    SECOND_ASSERTION, SKILL_CATEGORY, SNAPSHOT
}
