package com.zweigbergk.speedswede.util.async;

public enum PromiseNeed {
    ID, NAME, FIRST_USER, SECOND_USER, LIST, ASSERTION, NOTIFICATIONS, LANGUAGE, CHAT,
    FIRST_ASSERTION, SECOND_ASSERTION, SKILL_CATEGORY, SNAPSHOT
}
