package com.zweigbergk.speedswede.util;

public enum ProductLock {
    ID, NAME, TIMESTAMP, FIRST_USER, SECOND_USER, LIST, MESSAGE_LIST, ASSERTION, NOTIFICATIONS,
    LANGUAGE, USAGE, LAYOUT_MANAGER, CHAT, TRANSLATION
}
