package com.zweigbergk.speedswede.util;

public enum ProductLock {
    ID, NAME, TIMESTAMP, FIRST_USER, SECOND_USER, LIST, MESSAGE_LIST, ASSERTION, NOTIFICATIONS,
    LANGUAGE, SWEDISH_SKILL, STRANGER_SWEDISH_SKILL, LAYOUT_MANAGER, CHAT, TRANSLATION
}
